<a href="https://colab.research.google.com/github/wdchen2000/libgtop2.2/blob/master/Pytorch_by_Sentdex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## simple PyTorch exercise - https://www.youtube.com/watch?v=BzcBsTou0C0

In [6]:
!pip3 install torch
import torch

x = torch.Tensor([5, 30])
y = torch.Tensor([2, 1])
print(x*y)

tensor([10., 30.])


In [8]:
x = torch.zeros([2, 5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [10]:
x.shape

torch.Size([2, 5])

In [17]:
y = torch.rand([2,5])
print(y)

tensor([[0.7187, 0.3944, 0.7064, 0.1855, 0.7081],
        [0.3979, 0.5471, 0.6278, 0.9955, 0.9419]])


In [19]:
y

tensor([[0.7187, 0.3944, 0.7064, 0.1855, 0.7081],
        [0.3979, 0.5471, 0.6278, 0.9955, 0.9419]])

In [21]:
y.view([1,10])

tensor([[0.7187, 0.3944, 0.7064, 0.1855, 0.7081, 0.3979, 0.5471, 0.6278, 0.9955,
         0.9419]])

In [23]:
y 

tensor([[0.7187, 0.3944, 0.7064, 0.1855, 0.7081],
        [0.3979, 0.5471, 0.6278, 0.9955, 0.9419]])

here, we can view y[2,5] differently, say, [1,10] but y maintains its original shape, until we reshape it later
